c_compiler:                # [win]
  - vs2019                 # [win]
cxx_compiler:              # [win]
  - vs2019                 # [win]
channel_sources:
  - conda-forge
is_abi3:
  - true
python_min:
  - '3.11'
