{% set name = "perspective" %}
{% set pypi_name = "perspective-python" %}
{% set version = "2.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/{{ pypi_name }}-{{ version }}.tar.gz
  sha256: ad095e201c35848853092f7694383e2194855d75c2abde424efd69b8640692d1
  patches:
    - patches/0001-pybind_cmake.patch  # [win]
    - patches/0002-use-boost-shared.patch

build:
  number: 1
  script:
    - rm  -f perspective/table/libbinding.so perspective/table/libpsp.so  # [not win]
    - del /f "perspective\table\libbinding.so" "perspective\table\libpsp.so"  # [win]
    - {{ PYTHON }} -m pip install . -vv  # [not win]
    - set PSP_GENERATOR=Visual Studio 16 2019  # [win]
    - {{ PYTHON }} setup.py build_ext install --single-version-externally-managed  --record=record.txt  # [win]
requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform and not win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [not win]
    - jupyter_packaging <=1
  host:
    - boost
    - jupyter_packaging <=1
    - nodejs
    - numpy
    - pip
    - pybind11
    - python
    - yarn
  run:
    - python
    - boost
    # base
    - ipywidgets >=7.5.1,<9
    - future >=0.16.0,<1
    - {{ pin_compatible('numpy') }}
    - pandas >=0.22.0,<3
    - python-dateutil >=2.8.0,<3
    - traitlets >=4.3.2,<6
  run_constrained:
    # aiohttp
    - aiohttp >=3,<4
    # jupyter
    - jupyterlab >=3.2,<4
    # fastapi/starlette
    - fastapi >=0.70,<1
    - starlette >=0.20,<1
    # tornado
    - tornado >=4.5.3,<7

test:
  imports:
    - perspective
    - perspective.table

outputs:
  - name: perspective
  - name: perspective-python
    build:
      noarch: python
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage("perspective", exact=True) }}

  # TODO this is supposed to work, but fails with weird
  # bugs. Try again in the future
  # - name: perspective_python
  #   build:
  #     noarch: python
  #   requirements:
  #     host:
  #       - python
  #     run:
  #       - python
  #       - {{ pin_subpackage("perspective", exact=True) }}

about:
  home: http://github.com/finos/perspective
  license: Apache-2.0
  license_family: Apache
  license_file: dist/LICENSE
  summary: Streaming pivot visualization via WebAssembly
  description: Streaming pivot visualization via WebAssembly
  dev_url: https://github.com/finos/perspective

extra:
  recipe-maintainers:
    - timkpaine
    - texodus
    - sc1f
