{% set name = "perspective" %}
{% set version = "3.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/finos/perspective.git
  git_rev: v3.1.1
  patches:
    - patches/0001-delete-lint-package.patch
    - patches/0002-fix-flags.patch
    - patches/0003-delete-postinstall-scripts.patch
    - patches/0004-maturin-manylinux-off-external-cpp-feature.patch

build:
  number: 0
  skip: True  # [py<39 or py>=313]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin >=1.4,<2.0                     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    # git is required to build perspective, in order to clone its cmake
    # external projects. On windows, though, having git in the build
    # requirements causes conda-build to hang when cloning perspective's git
    # source, seems to be a conda-build bug.
    # Fortunately the CI pipeline still passes on Windows without the dep.  For
    # local Windows builds, install git in the base system.
    - git  # [not win]
    - cmake
    - make
    - pnpm
    - pkg-config
    - libprotobuf # for protoc
  host:
    - python
    - pip
    - maturin >=1.4,<2.0
  run:
    - python

test:
  imports:
    - perspective

about:
  home: http://github.com/finos/perspective
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE.md
  summary: Streaming pivot visualization via WebAssembly
  description: Streaming pivot visualization via WebAssembly
  dev_url: https://github.com/finos/perspective

extra:
  recipe-maintainers:
    - timkpaine
    - texodus
    - sc1f
