{% set name = "perspective" %}
{% set pypi_name = "perspective-python" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/{{ pypi_name }}-{{ version }}.tar.gz
  sha256: 97406dc4b7920ab8b744324f67eff8b008bf2045ea53fe2714371dceba8a3a4b

build:
  number: 1
  # skip: true  # [py<37 or win or osx]
  skip: True  # [py<37 or (win and vc<14)]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
  host:
    - python
    - pip
    - pybind11
    - boost
    - numpy >=1.13.1
    - pyarrow ==0.16.0
    - arrow-cpp ==0.16.0
  run:
    - python
    - ipywidgets >=7.5.1
    - {{ pin_compatible('numpy') }}
    - python-dateutil >=2.8.0
    - six >=1.11.0
    - traitlets >=4.3.2
    - pandas >=0.22.0
test:
  imports:
    - perspective
    - perspective.table

about:
  home: http://github.com/finos/perspective
  license: Apache-2.0
  license_family: Apache
  license_file: dist/LICENSE
  summary: Streaming pivot visualization via WebAssembly

  description: |
    Streaming pivot visualization via WebAssembly
  dev_url: https://github.com/finos/perspective

extra:
  recipe-maintainers:
    - timkpaine
    - texodus
    - neilslinger
    - sc1f
