{% set name = "perspective" %}
{% set pypi_name = "perspective-python" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/{{ pypi_name }}-{{ version }}.tar.gz
  sha256: f768f0b01d9c33f9af2258e3ce8942c7c8fe61c5febe84cf942a8ef7493d1045

build:
  number: 0
  skip: true  # [(win and vc<12) or nodejs<17 or py>37]

  script:
    - pwd  # [not win]
    - blerg
    - {{ PYTHON }} -m pip install . -vv  # [not win]
    - set PSP_GENERATOR=Visual Studio 14 2015  # [win]
    - {{ PYTHON }} setup.py build_ext install --single-version-externally-managed  --record=record.txt  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - sysroot_linux-64 2.17  # [linux64]
  host:
    - boost
    - flatbuffers
    - nodejs
    - numpy >=1.13.1
    - python
    - pip
    - pybind11
    - yarn
  run:
    - python
    - ipywidgets >=7.5.1
    - {{ pin_compatible('numpy') }}
    - pandas >=0.22.0
    - python-dateutil >=2.8.0
    - six >=1.11.0
    - tornado >=4.5.3
    - traitlets >=4.3.2
test:
  imports:
    - perspective
    - perspective.table

about:
  home: http://github.com/finos/perspective
  license: Apache-2.0
  license_family: Apache
  license_file: dist/LICENSE
  summary: Streaming pivot visualization via WebAssembly

  description: |
    Streaming pivot visualization via WebAssembly
  dev_url: https://github.com/finos/perspective

extra:
  recipe-maintainers:
    - timkpaine
    - texodus
    - sc1f
