{% set name = "perspective" %}
{% set version = "3.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/p/perspective-python/perspective_python-{{ version }}.tar.gz
    sha256: 3e6d759f98c65f07352d1a259656798451cbc38f0dacada0a17dd48582c3b8b3
    patches:
      - patches/fix_windows.diff

  - url: https://github.com/finos/perspective/archive/refs/tags/v{{ version }}.tar.gz
    sha256: fb20e3e6fe043a1d4482e992531082440d3756ca03633a539cd1ed7dfa6da09b
    folder: perspective-cpp
    patches:
      - patches/shared_boost.diff
      - patches/fix_flags.diff
      - patches/fix_arrow.diff

build:
  number: 0
  skip: true  # [py<39]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin >=1.4,<2.0                     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - cmake
    - make
    - libprotobuf
  host:
    - python
    - pip
    - maturin >=1.4,<2.0
    - libboost-devel
  run:
    - python
    - numpy
    - jinja2 >=2.0,<4
    - ipywidgets >=7.5.1,<9
    - pandas <3,>=0.22.0
    - python-dateutil <3,>=2.8.0
    - traitlets <6,>=4.3.2

test:
  imports:
    - perspective

outputs:
  - name: perspective
  - name: perspective-python
    requirements:
      build:
        - {{ stdlib("c") }}
      host:
        - python
      run:
        - python
        - perspective ={{ version }}

  # TODO this is supposed to work, but fails with weird
  # bugs. Try again in the future
  # - name: perspective_python
  #   build:
  #     noarch: python
  #   requirements:
  #     host:
  #       - python
  #     run:
  #       - python
  #       - {{ pin_subpackage("perspective", exact=True) }}

about:
  home: http://github.com/finos/perspective
  license: Apache-2.0
  license_family: Apache
  license_file:
    - perspective-cpp/LICENSE.md
  summary: Streaming pivot visualization via WebAssembly
  description: Streaming pivot visualization via WebAssembly
  dev_url: https://github.com/finos/perspective

extra:
  recipe-maintainers:
    - timkpaine
    - texodus
    - sc1f
