{% set name = "perspective" %}
{% set pypi_name = "perspective-python" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/{{ pypi_name }}-{{ version }}.tar.gz
  sha256: 7f0d6efee299f55761e59cd6fb95a7973e26b1d239963da1588447307151df7a

build:
  number: 1
  script:
    - {{ PYTHON }} -m pip install . -vv  # [not win]
    - set PSP_GENERATOR=Visual Studio 14 2015  # [win]
    - {{ PYTHON }} setup.py build_ext install --single-version-externally-managed  --record=record.txt  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform and not win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [not win]
  host:
    - boost
    - nodejs
    - numpy
    - pip
    - pybind11 <2.10  # [win]
    - pybind11  # [not win]
    - python
    - re2  # [not win]
    - yarn
  run:
    - ipywidgets >=7.5.1,<8
    - {{ pin_compatible('numpy') }}
    - pandas >=0.22.0
    - python
    - python-dateutil >=2.8.0
    - traitlets >=4.3.2

test:
  imports:
    - perspective
    - perspective.table

outputs:
   - name: perspective

   - name: perspective-python
     build:
       noarch: python
     requirements:
       host:
         - python
       run:
         - {{ pin_subpackage("perspective", exact=True) }}

   # - name: perspective_python
   #   build:
   #     noarch: python
   #   requirements:
   #     host:
   #       - python
   #     run:
   #       - {{ pin_subpackage("perspective-python", exact=True) }}

about:
  home: http://github.com/finos/perspective
  license: Apache-2.0
  license_family: Apache
  license_file: dist/LICENSE
  summary: Streaming pivot visualization via WebAssembly

  description: |
    Streaming pivot visualization via WebAssembly
  dev_url: https://github.com/finos/perspective

extra:
  recipe-maintainers:
    - timkpaine
    - texodus
    - sc1f
