{% set name = "perspective" %}
{% set version = "4.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/finos/perspective/releases/download/v{{ version }}/perspective_python-{{ version }}.tar.gz
  sha256: 0e026640fec929d0f8b0925f1ab3c6ed109d74c6f02cae8ba3073f45e75bc643

build:
  number: 0
  skip: true  # [py<39 or py>=314 or win or (osx and arm64)]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin >=1.4,<2.0                     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - git
    - cmake
    - make
    - pkg-config
  host:
    - python
    - pip
    - maturin >=1.4,<2.0
  run:
    - python

test:
  imports:
    - perspective

about:
  home: http://github.com/finos/perspective
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE.md
    - LICENSE_THIRDPARTY_cargo.yml
  summary: Streaming pivot visualization via WebAssembly
  description: Streaming pivot visualization via WebAssembly
  dev_url: https://github.com/finos/perspective

extra:
  recipe-maintainers:
    - timkpaine
    - texodus
    - sc1f
