{% set name = "perspective" %}
{% set version = "3.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/finos/perspective/releases/download/v{{ version }}/perspective_python-{{ version }}.tar.gz
  sha256: 5162736f6e2c1a1d0b3e5386c003708b1528973f077f282e698f5801036dc42b

build:
  number: 0
  skip: true  # [py<39 or py>=313]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin >=1.4,<2.0                     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - git
    - cmake
    - make
    - pkg-config
  host:
    - python
    - pip
    - maturin >=1.4,<2.0
  run:
    - python

test:
  imports:
    - perspective

about:
  home: http://github.com/finos/perspective
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE.md
    - LICENSE_THIRDPARTY_cargo.yml
  summary: Streaming pivot visualization via WebAssembly
  description: Streaming pivot visualization via WebAssembly
  dev_url: https://github.com/finos/perspective

extra:
  recipe-maintainers:
    - timkpaine
    - texodus
    - sc1f
